/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package figuras;

import javax.swing.JOptionPane;

/**
 *
 * @author liont
 */
public class JInternalEsfera extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalEsfera
     */
    public JInternalEsfera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRadio = new javax.swing.JLabel();
        Radio = new javax.swing.JTextField();
        CArea = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        CVolumen = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setTitle("Cálculo Área y Volumen Esfera");

        LabelRadio.setText("Radio");

        CArea.setText("Calcular Area");
        CArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAreaActionPerformed(evt);
            }
        });

        Clean.setText("Limpiar");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        CVolumen.setText("Calcular Volumen");
        CVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVolumenActionPerformed(evt);
            }
        });

        Exit.setText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(LabelRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRadio)
                    .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CArea)
                    .addComponent(CVolumen))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clean)
                    .addComponent(Exit))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        Radio.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void CVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVolumenActionPerformed
       try { 
       double radio = Double.parseDouble(Radio.getText());
       Esfera EsferaX = new Esfera(radio);
       JOptionPane.showMessageDialog(null, 
               "El valor del volumen en unidades cubicas es: " + String.valueOf(EsferaX.CalcVolumen()));
       }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se han introducido caracteres no numericos o faltan campos por llenar");
       }catch(ArithmeticException ex){JOptionPane.showMessageDialog(null, "Operacion No Valida");}
    }//GEN-LAST:event_CVolumenActionPerformed

    private void CAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAreaActionPerformed
       try { 
       double radio = Double.parseDouble(Radio.getText());
       Esfera EsferaX = new Esfera(radio);
       JOptionPane.showMessageDialog(null, 
               "El valor del area en unidades cuadradas es: " + String.valueOf(EsferaX.CalcArea()));
       }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se han introducido caracteres no numericos o faltan campos por llenar");
       }catch(ArithmeticException ex){JOptionPane.showMessageDialog(null, "Operacion No Valida");}
    }//GEN-LAST:event_CAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CArea;
    private javax.swing.JButton CVolumen;
    private javax.swing.JButton Clean;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel LabelRadio;
    private javax.swing.JTextField Radio;
    // End of variables declaration//GEN-END:variables
}
