/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package figuras;
import javax.swing.JOptionPane;
/**
 *
 * @author liont
 */
public class JInternalCilindro extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalCilindro
     */
    public JInternalCilindro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRadio = new javax.swing.JLabel();
        LabelAltura = new javax.swing.JLabel();
        CArea = new javax.swing.JButton();
        CVolumen = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        Altura = new javax.swing.JTextField();
        Radio = new javax.swing.JTextField();
        SubExit = new javax.swing.JButton();

        setTitle("Cálculo Área y Volumen Cilindro");

        LabelRadio.setText("Radio");

        LabelAltura.setText("Altura");

        CArea.setText("Calcular Area");
        CArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAreaActionPerformed(evt);
            }
        });

        CVolumen.setText("Calcular Volumen");
        CVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVolumenActionPerformed(evt);
            }
        });

        Clean.setText("Limpiar");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        SubExit.setText("Salir");
        SubExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelAltura)
                            .addComponent(LabelRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Altura, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(Radio)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CArea, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVolumen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRadio)
                    .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelAltura)
                    .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CVolumen)
                    .addComponent(Clean))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CArea)
                    .addComponent(SubExit))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAreaActionPerformed
       try { 
       double radio = Double.parseDouble(Radio.getText());
       double altura = Double.parseDouble(Altura.getText());
       Cilindro CilindroX = new Cilindro(radio,altura);
       JOptionPane.showMessageDialog(null, 
               "El valor del area en unidades cuadradas es: " + String.valueOf(CilindroX.CalcArea()));
       }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se han introducido caracteres no numericos o faltan campos por llenar");
       }catch(ArithmeticException ex){JOptionPane.showMessageDialog(null, "Operacion No Valida");}
    }//GEN-LAST:event_CAreaActionPerformed

    private void CVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVolumenActionPerformed
        try { 
       double radio = Double.parseDouble(Radio.getText());
       double altura = Double.parseDouble(Altura.getText());
       Cilindro CilindroX = new Cilindro(radio,altura);
       JOptionPane.showMessageDialog(null, 
               "El valor del volumen en unidades cubicas es: " + String.valueOf(CilindroX.CalcVolumen()));
       }catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Se han introducido caracteres no numericos o faltan campos por llenar");
       }catch(ArithmeticException ex){JOptionPane.showMessageDialog(null, "Operacion No Valida");}
    }//GEN-LAST:event_CVolumenActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        Radio.setText("");
        Altura.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void SubExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_SubExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Altura;
    private javax.swing.JButton CArea;
    private javax.swing.JButton CVolumen;
    private javax.swing.JButton Clean;
    private javax.swing.JLabel LabelAltura;
    private javax.swing.JLabel LabelRadio;
    private javax.swing.JTextField Radio;
    private javax.swing.JButton SubExit;
    // End of variables declaration//GEN-END:variables
}
