/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figuras;

/**
 *
 * @author liont
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CilindroCall = new javax.swing.JMenuItem();
        EsferaCall = new javax.swing.JMenuItem();
        PiramideCall = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SalirCall = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio Interfaz Gráfica de Usuario - Pagina 495\n");

        Background.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jMenu1.setText("Figuras Geometricas");

        CilindroCall.setText("Cilindro");
        CilindroCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CilindroCallActionPerformed(evt);
            }
        });
        jMenu1.add(CilindroCall);

        EsferaCall.setText("Esfera");
        EsferaCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsferaCallActionPerformed(evt);
            }
        });
        jMenu1.add(EsferaCall);

        PiramideCall.setText("Piramide");
        PiramideCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiramideCallActionPerformed(evt);
            }
        });
        jMenu1.add(PiramideCall);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Archivo");

        SalirCall.setText("Salir");
        SalirCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCallActionPerformed(evt);
            }
        });
        jMenu3.add(SalirCall);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CilindroCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CilindroCallActionPerformed
       JInternalCilindro JX = new JInternalCilindro();
       Background.add(JX);
       JX.setClosable(true);
       JX.setVisible(true);
    }//GEN-LAST:event_CilindroCallActionPerformed

    private void SalirCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCallActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirCallActionPerformed

    private void EsferaCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsferaCallActionPerformed
       JInternalEsfera JX = new JInternalEsfera();
       Background.add(JX);
       JX.setClosable(true);
       JX.setVisible(true);
    }//GEN-LAST:event_EsferaCallActionPerformed

    private void PiramideCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiramideCallActionPerformed
       JInternalPiramide JX = new JInternalPiramide();
       Background.add(JX);
       JX.setClosable(true);
       JX.setVisible(true);
    }//GEN-LAST:event_PiramideCallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Background;
    private javax.swing.JMenuItem CilindroCall;
    private javax.swing.JMenuItem EsferaCall;
    private javax.swing.JMenuItem PiramideCall;
    private javax.swing.JMenuItem SalirCall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
